/*
 * Copyright 2025-2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.swedenconnect.testclient.controllers;

import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.util.Pair;
import com.nimbusds.jwt.EncryptedJWT;
import com.nimbusds.jwt.JWT;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.PlainJWT;
import com.nimbusds.jwt.SignedJWT;
import com.nimbusds.oauth2.sdk.ParseException;
import com.nimbusds.oauth2.sdk.ResponseType;
import com.nimbusds.oauth2.sdk.Scope;
import com.nimbusds.oauth2.sdk.id.ClientID;
import com.nimbusds.oauth2.sdk.id.State;
import com.nimbusds.oauth2.sdk.pkce.CodeChallengeMethod;
import com.nimbusds.oauth2.sdk.pkce.CodeVerifier;
import com.nimbusds.openid.connect.sdk.Nonce;
import com.nimbusds.openid.connect.sdk.OIDCClaimsRequest;
import com.nimbusds.openid.connect.sdk.claims.ACR;
import net.minidev.json.JSONObject;
import se.swedenconnect.testclient.oidc.RequestObjectFactory;

import java.net.URI;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Resolves the parameters of an OIDC authentication request from the editable UI model, converting them into the
 * Nimbus types and deciding whether a parameter goes into the request URL or into the request object.
 * <p>
 * Every parameter is placed according to its two check boxes: "In Request" ({@code valuePresent}) puts it in the
 * request URL and "In Request Body" ({@code requestBody}) puts it in the request object. The boxes are independent,
 * so a parameter may appear in both locations, in one, or in none. Nothing is added to make the request compliant.
 * </p>
 * <p>
 * A resolver and the request object resolver obtained from {@link #toRequestObjectResolver()} share the values
 * generated by the server (state, nonce and code verifier), so a value that appears in both locations is the same.
 * Create a new resolver for each authentication request.
 * </p>
 * <p>
 * {@code state}, {@code nonce}, {@code prompt}, {@code acr_values}, {@code client_id} and {@code response_type} may
 * carry a different value in each location when
 * {@link AdvancedOptionsParamterModel#getAllowDifferentValues() different values} are allowed and the parameter is
 * placed in both, see {@link #valueFor(ModelParameter)}. Nothing is compared or corrected - the values are sent as
 * they were entered.
 * </p>
 *
 * @author Martin Lindström
 * @author Felix Hellman
 */
public class AuthorizationParameterResolver {

  /** The session attribute under which the code challenge method and code verifier of the request are saved. */
  public static final String CODE_VERIFIER_ATTRIBUTE = "code_verifier";

  private final OIDCAuthnRequestParameterModel model;
  private final boolean forRequestBody;
  private final BiConsumer<String, Object> saveFunction;
  private final Map<String, Object> resolvedValues;

  /**
   * Constructor.
   *
   * @param model the request parameter model
   * @param forRequestBody whether this resolver resolves the parameters of the request object (otherwise of the URL)
   * @param saveFunction function saving state that is needed later in the flow (e.g., the code verifier)
   */
  public AuthorizationParameterResolver(final OIDCAuthnRequestParameterModel model, final boolean forRequestBody,
      final BiConsumer<String, Object> saveFunction) {
    this(model, forRequestBody, saveFunction, new HashMap<>());
  }

  private AuthorizationParameterResolver(final OIDCAuthnRequestParameterModel model, final boolean forRequestBody,
      final BiConsumer<String, Object> saveFunction, final Map<String, Object> resolvedValues) {
    this.model = model;
    this.forRequestBody = forRequestBody;
    this.saveFunction = saveFunction;
    this.resolvedValues = resolvedValues;
  }

  private boolean isSelected(final ModelParameter parameter) {
    return this.isSelected(parameter.getValuePresent(), parameter.getRequestBody());
  }

  private boolean isSelected(final Boolean valuePresent, final Boolean requestBody) {
    return this.forRequestBody ? Boolean.TRUE.equals(requestBody) : Boolean.TRUE.equals(valuePresent);
  }

  /**
   * Gets the value of a parameter for this location. A parameter that is placed in both locations carries a value of
   * its own for the request object when different values are allowed; otherwise one value is sent in every location
   * it is placed in.
   *
   * @param parameter the parameter
   * @return the value for this location
   */
  private String valueFor(final ModelParameter parameter) {
    if (this.forRequestBody
        && Boolean.TRUE.equals(this.model.getAdvanced().getAllowDifferentValues())
        && Boolean.TRUE.equals(parameter.getValuePresent())
        && Boolean.TRUE.equals(parameter.getRequestBody())
        && parameter.getRequestBodyValue() != null) {
      return parameter.getRequestBodyValue();
    }
    return parameter.getValue();
  }

  /**
   * Gets a value that the server generates when the parameter is left empty. The generated value is shared between
   * the two locations, so a parameter that is placed in both, and left empty in both, carries the same value in each.
   */
  @SuppressWarnings("unchecked")
  private <T> Optional<T> getServerGeneratedValue(
      final String name,
      final ModelParameter parameter,
      final Supplier<T> defaultValueSupplier,
      final Function<String, T> transformFunction) {
    if (!this.isSelected(parameter)) {
      return Optional.empty();
    }
    final String value = this.valueFor(parameter);
    if (!Objects.isNull(value) && !value.isBlank()) {
      return Optional.of(transformFunction.apply(value));
    }
    return Optional.of((T) this.resolvedValues.computeIfAbsent(name, n -> defaultValueSupplier.get()));
  }

  private <T> Optional<T> getValue(final ModelParameter parameter, final Function<String, T> transformFunction) {
    if (this.isSelected(parameter)) {
      return Optional.of(transformFunction.apply(parameter.getValue()));
    }
    return Optional.empty();
  }

  /**
   * As {@link #getValue(ModelParameter, Function)}, for a parameter that may carry a different value in the request
   * object, see {@link #valueFor(ModelParameter)}.
   */
  private <T> Optional<T> getSplitValue(final ModelParameter parameter, final Function<String, T> transformFunction) {
    if (this.isSelected(parameter)) {
      return Optional.of(transformFunction.apply(this.valueFor(parameter)));
    }
    return Optional.empty();
  }

  public Optional<State> getState() {
    return this.getServerGeneratedValue("state", this.model.getAdvanced().getState(), State::new, State::new);
  }

  public Optional<Nonce> getNonce() {
    return this.getServerGeneratedValue("nonce", this.model.getAdvanced().getNonce(), Nonce::new, Nonce::new);
  }

  public Optional<URI> getRedirectionURI() {
    return this.getValue(this.model.getRedirectUri(), URI::create);
  }

  public Optional<ClientID> getClientId() {
    return this.getSplitValue(this.model.getClientId(), ClientID::new);
  }

  /**
   * Gets the scope for this location. The URL and the request object each have their own scope value, see
   * {@link OIDCAuthnRequestParameterModel#getRequestBodyScope()}.
   *
   * @return the scope, or an empty optional if no scope is placed here or the scope value is blank
   */
  public Optional<Scope> getScope() {
    final ModelParameter scope = this.model.getScope();
    if (!this.isSelected(scope)) {
      return Optional.empty();
    }
    final String value = this.forRequestBody && this.model.getRequestBodyScope() != null
        ? this.model.getRequestBodyScope()
        : scope.getValue();
    if (Objects.isNull(value) || value.isBlank()) {
      return Optional.empty();
    }
    return Optional.of(new Scope(value.trim().split("\\s+")));
  }

  /**
   * Gets the user message if it is placed in this location.
   *
   * @return the user message model, or an empty optional if the user message is not placed here
   */
  public Optional<OidcMessageParameterModel> getUserMessage() {
    return Optional.ofNullable(this.model.getUserMessage())
        .filter(um -> this.isSelected(um.getValuePresent(), um.getRequestBody()));
  }

  /**
   * Gets the sign request if it is placed in this location.
   *
   * @return the sign request model, or an empty optional if the sign request is not placed here
   */
  public Optional<SignatureParameterModel> getSignMessage() {
    return Optional.ofNullable(this.model.getSignMessage())
        .filter(sm -> this.isSelected(sm.getValuePresent(), sm.getRequestBody()));
  }

  /**
   * Gets the JWT carrying the sign request in the request URL, see
   * {@link RequestObjectFactory#getSignRequestJWT(OIDCAuthnRequestParameterModel, Function)}. The request object
   * carries the sign request as a JSON object instead, so for the request object the result is always empty.
   *
   * @param kidToJwkFunction function giving the key for a key ID
   * @return the JWT, or an empty optional if the sign request is not placed in the request URL
   * @throws JOSEException for signing or encryption errors
   * @throws ParseException if the sign request is not a valid claims set
   */
  public Optional<JWT> getSignRequestJWT(final Function<String, JWK> kidToJwkFunction)
      throws JOSEException, ParseException {
    if (this.forRequestBody || this.getSignMessage().isEmpty()) {
      return Optional.empty();
    }
    return Optional.of(RequestObjectFactory.getSignRequestJWT(this.model, kidToJwkFunction));
  }

  public Optional<ResponseType> getResponseType() {
    return this.getSplitValue(this.model.getAdvanced().getResponseType(), rt -> {
      return new ResponseType(rt.split(" "));
    });
  }

  public Optional<List<ACR>> getAcrValues() {
    return this.getSplitValue(this.model.getAcrValues(),
        value -> Arrays.stream(value.split("\\s+")).map(ACR::new).toList());
  }

  /**
   * Gets the {@code prompt} value for this location - a space-separated list of prompt values (OpenID Connect Core
   * 1.0, section 3.1.2.1). The value is sent exactly as it was built: it is not parsed into the request library's
   * {@link com.nimbusds.openid.connect.sdk.Prompt}, which rejects unknown values and would drop duplicates, so that
   * the test client can send combinations that break the specification.
   *
   * @return the prompt value, or an empty optional if no prompt is placed here or its value is blank
   */
  public Optional<String> getPrompt() {
    return this.getSplitValue(this.model.getAdvanced().getPrompt(), value -> value)
        .filter(value -> !value.isBlank());
  }

  public Optional<String> getLoginHint() {
    return this.getValue(this.model.getAdvanced().getLoginHint(), v -> v);
  }

  /**
   * Gets the {@code max_age} value for this location. The value must be a whole number of 0 or above (OpenID Connect
   * Core 1.0, section 3.1.2.1); a row that is on but holds anything else is treated as off, so that the request is
   * sent without {@code max_age}.
   *
   * @return the max age in seconds, or an empty optional if no max age is placed here or its value is not a whole
   *     number of 0 or above
   */
  public Optional<Integer> getMaxAge() {
    final ModelParameter maxAge = this.model.getAdvanced().getMaxAge();
    if (maxAge == null || !this.isSelected(maxAge)) {
      return Optional.empty();
    }
    final String value = Optional.ofNullable(maxAge.getValue()).map(String::trim).orElse("");
    if (!value.matches("\\d+")) {
      return Optional.empty();
    }
    try {
      return Optional.of(Integer.valueOf(value));
    }
    catch (final NumberFormatException e) {
      // Larger than the request library can hold - the row is treated as off
      return Optional.empty();
    }
  }

  /**
   * Gets the PKCE code challenge method and code verifier for this location. PKCE is placed in a location only when
   * both the code challenge and the code challenge method are selected for it. The code verifier is shared with the
   * other location, and is saved under {@link #CODE_VERIFIER_ATTRIBUTE} for the token request.
   *
   * @return the code challenge method and code verifier, or an empty optional if PKCE is not placed here
   */
  public Optional<Pair<CodeChallengeMethod, CodeVerifier>> getCodeChallenge() {
    final Optional<CodeChallengeMethod> method = this.getValue(this.model.getAdvanced().getCodeChallengeMethod(),
        CodeChallengeMethod::new);
    if (method.isEmpty()) {
      return Optional.empty();
    }
    return this.getServerGeneratedValue(CODE_VERIFIER_ATTRIBUTE, this.model.getAdvanced().getCodeChallenge(),
            CodeVerifier::new, CodeVerifier::new)
        .map(verifier -> {
          final Pair<CodeChallengeMethod, CodeVerifier> codeChallenge = Pair.of(method.get(), verifier);
          this.saveFunction.accept(CODE_VERIFIER_ATTRIBUTE, codeChallenge);
          return codeChallenge;
        });
  }

  public Optional<JWT> requestBody(final Function<String, JWK> kidToJwtFunction) throws JOSEException, ParseException {
    final JWTClaimsSet claims = RequestObjectFactory.getClaims(
        model,
        this.toRequestObjectResolver()
    );
    if (claims.toJSONObject().size() <= 2) {
      return Optional.empty();
    }
    saveFunction.accept("jwt_claims", claims);
    if (model.getRequestObject().getSignRequest()) {
      final SignedJWT signedJWT = RequestObjectFactory.getSignedJWT(model, kidToJwtFunction, claims);
      saveFunction.accept("signed_jwt", signedJWT);
      if (model.getRequestObject().getEncryptRequest()) {
        final EncryptedJWT encryptedJWT = RequestObjectFactory.getEncryptedJWT(model, kidToJwtFunction, signedJWT);
        saveFunction.accept("encrypted_signed_jwt", encryptedJWT);
        return Optional.of(encryptedJWT);
      }
      return Optional.of(signedJWT);
    }
    final PlainJWT jwt = new PlainJWT(claims);
    saveFunction.accept("plain_jwt", jwt);
    if (model.getRequestObject().getEncryptRequest()) {
      final EncryptedJWT encryptedPlainJwt = RequestObjectFactory.getEncryptedJWT(model, kidToJwtFunction, jwt);
      saveFunction.accept("encrypted_plain_jwt", encryptedPlainJwt);
      return Optional.of(encryptedPlainJwt);
    }
    return Optional.of(jwt);
  }

  /**
   * Gets the claims request if the claims are placed in this location. The claims follow their two boxes like every
   * other row, so the same claims may be sent in both locations; a request that only holds
   * {@link OIDCAuthnRequestParameterModel#getClaimInRequestBody()}, as templates and older exports do, sends them in
   * the request object when it is set and in the request URL otherwise.
   *
   * @return the claims request, or an empty optional if no claims are placed here
   * @throws ParseException for an invalid claims request
   */
  public Optional<OIDCClaimsRequest> getClaimRequest() throws ParseException {
    if (Objects.isNull(this.model.getClaims()) || this.model.getClaims().isEmpty()) {
      return Optional.empty();
    }
    final boolean inRequestBody = Boolean.TRUE.equals(this.model.getClaimInRequestBody());
    final boolean inRequest = Objects.isNull(this.model.getClaimInRequest())
        ? !inRequestBody
        : this.model.getClaimInRequest();
    if (this.forRequestBody ? inRequestBody : inRequest) {
      return Optional.of(OIDCClaimsRequest.parse(new JSONObject(this.model.getClaims())));
    }
    return Optional.empty();
  }

  public AuthorizationParameterResolver toRequestObjectResolver() {
    return new AuthorizationParameterResolver(this.model, true, this.saveFunction, this.resolvedValues);
  }
}
