name: Automated review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - run: mvn clean verify --no-transfer-progress
